version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - pip3 install boto3 behave sure
  build:
    commands:
      - echo Started on `date`
      - echo Testing Workspace...
      - behave
  post_build:
    commands:
      - echo Chef Install completed on `date`