version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - pip3 install boto3 behave
  build:
    commands:
      - echo Started on `date`
      - echo Installing Chef...
      - python3 scripts/execute_chef.py
  post_build:
    commands:
      - echo Chef Install completed on `date`