AWSTemplateFormatVersion: "2010-09-09"
Description: Continuous Delivery CodePipeline that automatically  build, tests, deploys the CS-260 Lab Environment
Parameters:
  GitHubToken:
    Type: String
    NoEcho: true
  GitHubUser:
    Type: String
    Default: stelligent
  GitHubRepoName:
    Type: String
    Default: bootstrap-windows-chef-node
  GitHubBranchName:
    Type: String
    Default: master
  S3Bucket:
    Description: S3 bucket containing the Chef Cookbooks
    Type: String
    Default: snhu-cookbooks
  Runlist:
    Description: Runlist for Workspace
    Type: String
    Default: "snhu-eclipse"
Resources:
  ManualApprovalStageGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: ManaulApprovalStageGroup
      Path: /
      Policies:
        -
          PolicyName: manual-approval-stage-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Deny
              Action:
              - codepipeline:PutApprovalResult
              Resource: "*"
  WorkspaceServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: rds-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                - "workspaces:*"
                Resource: "*"
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: codepipeline-service
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action: "*"
                Resource: "*"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        -
          PolicyName: lambda-workspaces-ssm
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action: 
                  - "workspaces:*"
                  - "ssm:*"
                  - "s3:*"
                  - "codepipeline:PutJobSuccessResult"
                  - "codepipeline:PutJobFailureResult"
                Resource: "*"
              -
                Action: 
                  - "logs:*"
                Effect: Allow, 
                Resource: "arn:aws:logs:*:*:*"
  LambdaInstallChefFn:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: some-bucket
        S3Key: some-key
      Handler: remote-workspaces.chef_handler
      Role: !Ref LambaRole
      Runtime: python3.6
      Timeout: 300
      VpcConfig:
        SecurityGroupIds:
          - sg-3e270b4f
        SubnetIds:
          - subnet-cba53de7
          - subnet-be2674f6
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref "S3Bucket"
        Type: S3
      RoleArn: !GetAtt [CodePipelineRole, Arn]
      Stages:
        - Name: Commit
          Actions:
          - Name: Commit
            ActionTypeId:
              Category: Source
              Owner: ThirdParty
              Provider: GitHub
              Version: 1
            OutputArtifacts:
              - Name: CS-260
            Configuration:
              Owner: !Ref GitHubUser
              Repo: !Ref GitHubRepoName
              Branch: !Ref GitHubBranchName
              OAuthToken: !Ref GitHubToken
        - Name: Build
          Actions:
          - Name: Workspace Provisioning
            RunOrder: 1
            ActionTypeId:
              Category: Invoke
              Owner: AWS
              Version: 1
              Provider: Lambda
            Configuration: {
              FunctionName: !Ref WorkspaceCreaterLambda
              UserParameters: !Ref Runlist
            }
            InputArtifacts:
              - Name: CS-260
          - Name: Install Chef
            RunOrder: 2
            ActionTypeId:
              Category: Invoke
              Owner: AWS
              Version: 1
              Provider: Lambda
            Configuration: {
              "FunctionName": {
                "Ref": "LambdaInstallChefFn"
              }
            }

        - Name: Production
          Actions:
          - Name: Approval
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Version: 1
              Provider: Manual